subDF <- household_power_consumption[as.Date(household_power_consumption$Date, "%d/%m/%Y") >= as.Date("2007-02-01", "%Y-%m-%d") & as.Date(household_power_consumption$Date, "%d/%m/%Y") <= as.Date("2007-02-02", "%Y-%m-%d"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3", "Date", "Time")]
subDF$Date <- strptime(paste(as.character(subDF$Date), as.character(subDF$Time), sep = " "), "%d/%m/%Y %H:%M:%S")
subDF$Sub_metering_1 <- as.numeric(as.character(subDF$Sub_metering_1))
subDF$Sub_metering_2 <- as.numeric(as.character(subDF$Sub_metering_2))
subDF$Sub_metering_3 <- as.numeric(as.character(subDF$Sub_metering_3))
plot(subDF$Date, subDF$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Submetering", col = "black")
lines(subDF$Date, subDF$Sub_metering_2, col = "red")
lines(subDF$Date, subDF$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, 'plot3.png')
dev.off()
